apiVersion: v1
kind: Service
metadata:
  name: hostname-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: hostname
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080